export const resList = [
  {
    type: "restaurant",
    data: {
      id: "466657",
      name: "Punjabi Angithi (Vegorama Group)",
      locality: "Shri Aurbindo Marg",
      areaName: "Adchini",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "Chinese", "Tandoor", "rolls"],
      avgRating: 3.3,
      veg: true,
      parentId: "465050",
      avgRatingString: "3.3",
      totalRatingsString: "55K+",
      promoted: true,
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/19/9e324e6d-ca24-4d83-b1cb-b351d94e8e9a_466657.jpg",
      adTrackingId:
        "cid=f045cddc-d9b5-4157-b692-4f208278e3a2~p=0~adgrpid=f045cddc-d9b5-4157-b692-4f208278e3a2#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=466657~plpr=COLLECTION~eid=7a712fca-4378-400a-97dd-7e37d733c52e~srvts=1787737003717~collid=83633",
      sla: {
        deliveryTime: 40,
        lastMileTravel: 2.8,
        serviceability: "SERVICEABLE",
        slaString: "40-50 mins",
        lastMileTravelString: "2.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 00:00:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "BENEFITS",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466658",
      name: "Biryani Blues",
      locality: "Green Park",
      areaName: "Green Park",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "Kebabs", "North Indian"],
      avgRating: 3.5,
      veg: false,
      parentId: "465051",
      avgRatingString: "3.5",
      totalRatingsString: "20K+",
      promoted: false,
      cloudinaryImageId: "tjbeksybwfqiwtxjqdns",
      adTrackingId: "cid=bb-01~p=0~adgrpid=bb-01#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 30,
        lastMileTravel: 3.1,
        serviceability: "SERVICEABLE",
        slaString: "30-40 mins",
        lastMileTravelString: "3.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 01:00:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "40% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "OFFERS",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466659",
      name: "The Burger Club",
      locality: "Saket",
      areaName: "Saket",
      costForTwo: "₹450 for two",
      cuisines: ["American", "Fast Food", "Burgers"],
      avgRating: 4.4,
      veg: false,
      parentId: "465052",
      avgRatingString: "4.4",
      totalRatingsString: "18K+",
      promoted: true,
      cloudinaryImageId: "punoxwfezgjyrice8u1o",
      adTrackingId: "cid=bc-02~p=0~adgrpid=bc-02#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 25,
        lastMileTravel: 2.5,
        serviceability: "SERVICEABLE",
        slaString: "25-35 mins",
        lastMileTravelString: "2.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 00:30:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "30% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "SAVE MORE",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466660",
      name: "Kathi Junction",
      locality: "Maharani Bagh",
      areaName: "Maharani Bagh",
      costForTwo: "₹350 for two",
      cuisines: ["Kebabs", "Rolls", "Snacks"],
      avgRating: 3.8,
      veg: false,
      parentId: "465053",
      avgRatingString: "3.8",
      totalRatingsString: "22K+",
      promoted: false,
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/8/11/df8cd345-b193-4044-b8e6-9e5607b090e6_909996.JPG",
      adTrackingId: "cid=kj-03~p=0~adgrpid=kj-03#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 35,
        lastMileTravel: 2.9,
        serviceability: "SERVICEABLE",
        slaString: "35-45 mins",
        lastMileTravelString: "2.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 00:45:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "BENEFITS",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466661",
      name: "Veg Supreme",
      locality: "Defence Colony",
      areaName: "Defence Colony",
      costForTwo: "₹380 for two",
      cuisines: ["Veg Indian", "Italian", "Desserts"],
      avgRating: 4.5,
      veg: true,
      parentId: "465054",
      avgRatingString: "4.5",
      totalRatingsString: "30K+",
      promoted: true,
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/11/14/5a8893c8-d300-45b6-ac3c-cdaa6e195ad8_1115062.JPG",
      adTrackingId: "cid=vs-04~p=0~adgrpid=vs-04#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 28,
        lastMileTravel: 2.2,
        serviceability: "SERVICEABLE",
        slaString: "28-38 mins",
        lastMileTravelString: "2.2 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 00:20:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "20% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "SAVE MORE",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466662",
      name: "Momos & More",
      locality: "Dwarka Sector 12",
      areaName: "Dwarka",
      costForTwo: "₹300 for two",
      cuisines: ["Chinese", "Momos", "Snacks"],
      avgRating: 4.0,
      veg: false,
      parentId: "465055",
      avgRatingString: "4.0",
      totalRatingsString: "12K+",
      promoted: false,
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/8/26/9d3647ef-3a1c-4ed7-9244-5c38e3079337_397323.JPG",
      adTrackingId: "cid=mm-05~p=0~adgrpid=mm-05#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 24,
        lastMileTravel: 1.8,
        serviceability: "SERVICEABLE",
        slaString: "24-34 mins",
        lastMileTravelString: "1.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 01:15:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "35% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "BENEFITS",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466663",
      name: "Tandoori Treat",
      locality: "Rajouri Garden",
      areaName: "Rajouri Garden",
      costForTwo: "₹600 for two",
      cuisines: ["North Indian", "Tandoor", "Chinese"],
      avgRating: 3.3,
      veg: false,
      parentId: "465056",
      avgRatingString: "3.3",
      totalRatingsString: "41K+",
      promoted: true,
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/15/a7166e03-1ab6-4c79-b32b-1c84d6452418_157766.jpg",
      adTrackingId: "cid=tt-06~p=0~adgrpid=tt-06#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 42,
        lastMileTravel: 3.4,
        serviceability: "SERVICEABLE",
        slaString: "42-52 mins",
        lastMileTravelString: "3.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 00:55:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "60% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "BEST DEAL",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466664",
      name: "Pizza Pie",
      locality: "Vasant Kunj",
      areaName: "Vasant Kunj",
      costForTwo: "₹500 for two",
      cuisines: ["Pizza", "Italian", "Fast Food"],
      avgRating: 3.5,
      veg: false,
      parentId: "465057",
      avgRatingString: "3.5",
      totalRatingsString: "16K+",
      promoted: true,
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/11/14/5a8893c8-d300-45b6-ac3c-cdaa6e195ad8_1115062.JPG",
      adTrackingId: "cid=pp-07~p=0~adgrpid=pp-07#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 31,
        lastMileTravel: 2.7,
        serviceability: "SERVICEABLE",
        slaString: "31-41 mins",
        lastMileTravelString: "2.7 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 00:40:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "45% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "OFFERS",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466665",
      name: "Saffron Bowl",
      locality: "Patel Nagar",
      areaName: "Patel Nagar",
      costForTwo: "₹420 for two",
      cuisines: ["North Indian", "Chinese", "Desserts"],
      avgRating: 4.6,
      veg: true,
      parentId: "465058",
      avgRatingString: "4.6",
      totalRatingsString: "45K+",
      promoted: true,
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2026/8/26/9d3647ef-3a1c-4ed7-9244-5c38e3079337_397323.JPG",
      adTrackingId: "cid=sb-08~p=0~adgrpid=sb-08#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 33,
        lastMileTravel: 2.1,
        serviceability: "SERVICEABLE",
        slaString: "33-43 mins",
        lastMileTravelString: "2.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 00:35:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "50% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "PARTY DEAL",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "466666",
      name: "Dosa Delight",
      locality: "Karol Bagh",
      areaName: "Karol Bagh",
      costForTwo: "₹280 for two",
      cuisines: ["South Indian", "Chinese", "Breakfast"],
      avgRating: 2.9,
      veg: true,
      parentId: "465059",
      avgRatingString: "2.9",
      totalRatingsString: "19K+",
      promoted: false,
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/11/14/5a8893c8-d300-45b6-ac3c-cdaa6e195ad8_1115062.JPG",
      adTrackingId: "cid=dd-09~p=0~adgrpid=dd-09#ag1~mp=SWIGGY_IN~bl=FOOD",
      sla: {
        deliveryTime: 26,
        lastMileTravel: 1.9,
        serviceability: "SERVICEABLE",
        slaString: "26-36 mins",
        lastMileTravelString: "1.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2026-08-27 00:50:00",
        opened: true,
      },
      isOpen: true,
      type: "F",
      aggregatedDiscountInfoV3: {
        header: "25% OFF",
        discountTag: "FLAT DEAL",
        logoCtx: {
          text: "SAVE MORE",
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
    },
  },
];
